### ISSUE TITLE
Stuck in "Waiting for another flutter command to release the startup lock..." 

### ISSUE THREAD

**Issue by davidfranquet** [bitrise-steplib/bitrise-step-flutter-test#14]
Hello.
I'm trying to setup a flutter project and trying to run the step "Flutter Test" but it stuck in "Waiting for another flutter command to release the startup lock..." 

I've tried to add the script `killall -9 dart` before flutter test but doesn't work

**Comment by non-binary** [comment]
Hi @davidfranquet,

Can you please send a build link and enable support access in your project's settings?

**Comment by rohan20** [comment]
This is still an issue. Tried reaching out to Bitrise support but none of the suggestions worked.

**Comment by non-binary** [comment]
@rohan20

Can you please send a build link and enable support access in your project's settings?

**Comment by ldemyanenko** [comment]
We are experiencing same issue 
Loogs look like this 
+------------------------------------------------------------------------------+

| (8) flutter-test                                                             |
+------------------------------------------------------------------------------+
| id: flutter-test                                                             |
| version: 0.10.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-12-18T14:36:23Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- AdditionalParams: test/api_tests_runner.dart
- ProjectLocation: /Users/vagrant/git
- TestResultsDir: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/test_results075885842/test_result649846838
- GenerateCodeCoverageFiles: false
Running test
Command `tojunit` not found, installing...
$ flutter "pub" "global" "activate" "junitreport"
Resolving dependencies...
+ args 1.6.0
+ charcode 1.1.3
+ collection 1.14.13
+ convert 2.1.1
+ intl 0.16.1
+ junitreport 1.3.1
+ meta 1.2.4
+ path 1.7.0
+ petitparser 3.1.0
+ testreport 1.2.0
+ typed_data 1.2.0
+ xml 4.5.1
Downloading junitreport 1.3.1...
Downloading testreport 1.2.0...
Downloading charcode 1.1.3...
Downloading meta 1.2.4...
Downloading typed_data 1.2.0...
Downloading collection 1.14.13...
Downloading path 1.7.0...
Precompiling executables...
Precompiled junitreport:tojunit.
Installed executable tojunit.
Activated junitreport 1.3.1.
$ flutter "test" "--machine" "test/api_tests_runner.dart" [REDACTED] tojunit "--output" "./flutter_junit_test_results.xml"
Waiting for another flutter command to release the startup lock...
                                                                  
Completing test command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | flutter-test (exit code: 1)                                   | 1.8 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ithub.com/bitrise-steplib/bitrise-step-flutter-test/issues |
| Source: https://github.com/bitrise-steplib/bitrise-step-flutter-test         |
+---+---------------------------------------------------------------+----------+

**Comment by non-binary** [comment]
Hi @ldemyanenko, Can you please send a build link and enable support access?

**Comment by ldemyanenko** [comment]
@non-binary Here is the link https://app.bitrise.io/build/ea77f02514d4babf#?tab=log
We enabled support access

**Comment by non-binary** [comment]
Hi @ldemyanenko,

Please try https://stackoverflow.com/a/60801418 and https://stackoverflow.com/a/52873370. You can find the directory where flutter is installed by doing `which flutter`

**Comment by mateherber** [comment]
Hi @ldemyanenko,

The pasted log actually means that the test step has failed due to probably failing test case. I think it could go further than `Waiting for another...`. 

As for the missing test results there is an other issue (#13) which hopefully will be fixed with the next step version asap next year.

Happy Holidays! 🎄

**Comment by regmoraes** [comment]
Any updates on this? I'm having this problem too, my builds went from 9min to 20min because of this.

**Comment by Roland-Bak** [comment]
Hello there everyone 👋

Let me share some (hopefully) useful information regarding this error:

Every unit test goes through three phases: Arrange, Act, and Assert. As long as whatever you're trying to test goes wrong in the Assert phase, Flutter will give you a nice error message explaining what went wrong. 

The issue comes in when something is wrong with the Arrange or Act phases. In particular, if your test requires a dependency that isn't brought in correctly or if something is mocked incorrectly. 

Flutter, rather than giving you a nice detailed explanation of what's wrong, will freeze with the startup lock error. This is what the error you receive suggests.

Unfortunately this is an issue with Flutter itself, and what you can do is try to narrow down which test is causing the problem.

One thing you can try is to clear your cache and remove any caching step from you workflow. If this fixes the issue, then that would mean that Flutter was trying to pull in a bad cached dependency.

Hope this helps! 🙂
